#!/usr/bin/env php
<?php
	$output = exec('ssh pi@ssh.bobbydilley.co.uk "/opt/vc/bin/vcgencmd measure_temp"');
	
	$temp = -1;
	preg_match("/temp=(.*)'/", $output, $matches);
	if($matches) {
		$temp = $matches[1];
	}

	if($temp != -1) {
		if($temp > 40) {
			die("FAIL - Temperature is $temp which is above 30 degrees\n");
		} else {
			die("OKAY - Temperature is $temp which is below 30 degrees\n");
		}
	}
	
	die("FAIL \n");
?>
