#!/usr/bin/env php
<?php
	$message = $argv[1];
	$output = exec('curl -X POST -H "Content-Type: application/json" -d \'{"value1":"' . $message . '"}\' https://maker.ifttt.com/trigger/notification/with/key/<KEY_HERE>');
	
	die("OKAY \n");
?>
